-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

module(...)

function physicsData(scale)
	local physics = { data =
	{ 
		
		["purpleBumper"] = {
			
				{
					density = 2, friction = 0, bounce = 2, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -4.40430641174316, -23.160285949707  ,  3.21929740905762, -23.0007972717285  ,  13.1395530700684, -16.3341293334961  ,  15.3724098205566, -4.21291732788086  ,  -14.7711324691772, 16.9992027282715  ,  -15.0901117324829, -5.6483268737793  ,  -14.9306221008301, -12.3468894958496  ,  -11.4218502044678, -19.3644332885742  }
				}  ,
				{
					density = 2, friction = 0, bounce = 2, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   1.8157901763916, 26.4090909957886  ,  -3.92583656311035, 26.2496013641357  ,  -9.82695388793945, 23.5382776260376  ,  -13.1762361526489, 19.8700160980225  ,  -14.7711324691772, 16.9992027282715  ,  15.2129173278809, 2.96411514282227  ,  14.5749588012695, 18.5940990447998  ,  8.83333206176758, 24.4952154159546  }
				}  ,
				{
					density = 2, friction = 0, bounce = 2, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   13.1395530700684, -16.3341293334961  ,  3.21929740905762, -23.0007972717285  ,  8.99282455444336, -20.9593315124512  }
				}  ,
				{
					density = 2, friction = 0, bounce = 2, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   15.3724098205566, -4.21291732788086  ,  13.1395530700684, -16.3341293334961  ,  15.5318984985352, -10.4330139160156  }
				}  ,
				{
					density = 2, friction = 0, bounce = 2, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   15.2129173278809, 2.96411514282227  ,  -14.7711324691772, 16.9992027282715  ,  15.3724098205566, -4.21291732788086  }
				}  
		}
		
	} }

	-- apply scale factor
	local s = scale or 1.0
	for bi,body in pairs(physics.data) do
		for fi,fixture in ipairs(body) do
			for ci,coordinate in ipairs(fixture.shape) do
				fixture.shape[ci] = s * coordinate
			end
		end
	end
	
	function physics:get(name)
		return unpack(self.data[name])
	end
	
	return physics;
end


